name: Release Foundry Module

on:
  push:
    tags:
      - "v*"

permissions:
  contents: read   # keep global token read-only

jobs:
  build-release:
    runs-on: ubuntu-latest
    env:
      MODULE_DIR: modules/folder-api
      ZIP_BASENAME: folder-api
    steps:
      - uses: actions/checkout@v4

      - name: Set version/tag env
        run: |
          echo "TAG=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
          echo "ZIP_NAME=${ZIP_BASENAME}-${GITHUB_REF#refs/tags/}.zip" >> $GITHUB_ENV

      - name: Ensure module.json exists
        run: test -f "$MODULE_DIR/module.json"

      - name: Create flat ZIP from subdirectory
        working-directory: ${{ env.MODULE_DIR }}
        run: zip -r "$GITHUB_WORKSPACE/${{ env.ZIP_NAME }}" .

      - name: Create GitHub Release + upload asset
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.TAG }}
          files: ${{ github.workspace }}/${{ env.ZIP_NAME }}
          generate_release_notes: true
          token: ${{ secrets.RELEASE_TOKEN }}
